name: "Stale Issues Finder"
description: "Find what issues have been stale for a given time"
author: paritytech
branding:
  icon: zoom-in
  color: white
inputs:
  GITHUB_TOKEN:
    required: true
    description: The token to access the repo
  repo:
    required: false
    description: The repository to fetch the issues from
  owner:
    required: false
    description: The name of the org/user that owns the repository
  days-stale:
    required: false
    description: How many days have to pass to consider an action "stale"
    default: '5'
  noComments:
    required: false
    description: If true, it will only collect issues with NO comments.
    default: false
  ignoreAuthors:
    required: false
    description: Collections of usernames separated by commas that should be ignored if they are the author of the issue.
    type: string
  requiredLabels:
    required: false
    description: Collections of labels separated by commas that should be required when searching for a issue.
    type: string
outputs:
  repo:
    description: 'The name of the repo in owner/repo pattern'
  data:
    description: 'A JSON object with the data'
  message:
    description: 'A markdown formatted message'
  stale:
    description: 'Amount of stale issues. 0 if none found.'

runs:
  using: 'docker'
  image: 'docker://ghcr.io/paritytech/stale-issues-finder/action:0.0.6'
